platform :osx

podspec :path => "../BCDataStream.podspec"
pod 'BCDataStream', :path => "../BCDataStream.podspec"

target 'BCDataStreamExample Tests' do
    pod 'BCDataStream/Tests', :path => '../BCDataStream.podspec'
end
